apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zlinebot
spec:
  rules:
    - host: zlinebot.zeaz.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zlinebot
                port:
                  number: 80
