#!/usr/bin/env bash
set -euo pipefail

DOMAIN="${1:-zlinebot.zeaz.dev}"
OUT_FILE="${2:-.env}"

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required to generate secure secrets" >&2
  exit 1
fi

rand_base64() {
  openssl rand -base64 48 | tr -d '\n'
}

rand_hex() {
  openssl rand -hex 32
}

rand_hex_64() {
  openssl rand -hex 64
}

APP_URL="https://${DOMAIN}"
TIKTOK_REDIRECT_URI="${APP_URL}/api/auth/tiktok/callback"

cat >"${OUT_FILE}" <<EOF_ENV
# Auto-generated by scripts/generate-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
NODE_ENV=production
PORT=3000
DOMAIN=${DOMAIN}
APP_URL=${APP_URL}

JWT_SECRET=$(rand_hex_64)
SESSION_SECRET=$(rand_base64)
ENCRYPTION_KEY=$(rand_hex)
TENANT_API_KEY=$(rand_hex)
ML_GRPC_SECRET=$(rand_hex)

DATABASE_URL=postgresql://postgres:postgres@db:5432/zlinebot
POSTGRES_DB=zlinebot
POSTGRES_USER=zlinebot
POSTGRES_PASSWORD=$(rand_hex)

REDIS_URL=redis://redis:6379
REDIS_PASSWORD=$(rand_hex)
KAFKA_PASSWORD=$(rand_hex)
QDRANT_URL=http://qdrant:6333

LINE_CHANNEL_SECRET=$(rand_hex)
LINE_CHANNEL_ACCESS_TOKEN=$(rand_hex_64)
LINE_DEFAULT_TENANT_ID=demo
LINE_WEBHOOK_URL=${APP_URL}/webhook/line

TIKTOK_CLIENT_KEY=
TIKTOK_CLIENT_SECRET=
TIKTOK_REDIRECT_URI=${TIKTOK_REDIRECT_URI}
TIKTOK_WEBHOOK_SECRET=$(rand_hex)
TIKTOK_SCOPE=user.info.basic
TIKTOK_SHOP_API_BASE_URL=https://open-api.tiktokglobalshop.com
TIKTOK_SHOP_ACCESS_TOKEN=
TIKTOK_WEBHOOK_URL=${APP_URL}/webhook/tiktok

STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=

QUEUE_CONCURRENCY=5
AUTOMATION_WORKER_MODE=external

RATE_LIMIT=100
CORS_ORIGIN=${APP_URL}

# Cloudflare Tunnel
CLOUDFLARE_TUNNEL_TOKEN=
EOF_ENV

chmod 600 "${OUT_FILE}"
echo "✅ Generated ${OUT_FILE} for ${DOMAIN}"
