name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker
        run: docker build -t zlinebot .

      - name: Push
        run: |
          docker tag zlinebot registry.fly.io/zlinebot
          docker push registry.fly.io/zlinebot
